### ISSUE TITLE
不支持BitCode

### ISSUE THREAD

**Issue by taecg** [unity-plugins/BaiDu-Unity-Plugin#1]
当BitCode为Yes时会报错，有办法支持BitCode吗？

**Comment by unity-plugins** [comment]
如果百度sdk支持就可以支持的

**Comment by unity-plugins** [comment]
支持bitcode了

**Comment by taecg** [comment]
太赞了!

**Comment by taecg** [comment]
另外你做的BaiDu和Admob插件是否能同时集成在一个工程中呢?我之前试过会出现些问题，发布ＩＯＳ时会报错，安卓还没有测试

**Comment by unity-plugins** [comment]
有具体错误信息吗

**Comment by shi8tou** [comment]
Undefined symbols for architecture armv7:
  "_kSecValueData", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecReturnData", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_SecItemCopyMatching", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecClass", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecMatchLimit", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecClassGenericPassword", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecAttrService", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecMatchLimitOne", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecAttrAccount", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecAttrAccessibleAfterFirstUnlock", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_kSecAttrAccessible", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_SecItemDelete", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
  "_SecItemAdd", referenced from:
      +[BaiduMobAdDeviceInfo getAppSN] in BaiduPlugin.a(BaiduMobAdDeviceInfo.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
我在xcode中编译过程中报以上错，请问如何可以解决呢？谢谢

**Comment by unity-plugins** [comment]
已经更新百度 ios

**Comment by shi8tou** [comment]
太好了！

**Comment by unity-plugins** [comment]
需要 在xcode 工程里面加上  Security.framework   ，上面的_kSecValueData 无法找到错误会消除
