### ISSUE TITLE
scripting backend选项是il2cpp时找不到init方法

### ISSUE THREAD

**Issue by augustli2009** [unity-plugins/BaiDu-Unity-Plugin#4]
都是中国人我就不讲英文了。。。。

scripting backend选项设置为il2cpp的时候找不到__kminit方法，换成mono2x就可以了，，，，

but,you know,苹果强制要求开发者支持ipv6，就必须设置为il2cpp，而且il2cpp会比mono2x快不少，不是么。。。。

求解决。。。

**Comment by augustli2009** [comment]
妈个鸡，刚在真机上试了下貌似是好的。。。。奶奶个熊。。。。

**Comment by unity-plugins** [comment]
哈哈，那就star一个

**Comment by augustli2009** [comment]
start了，，，真机可以用，，模拟器不能用，，，真是，，，算了，，加个宏定义模拟器的时候不启动百度ad了
