### ISSUE TITLE
提交带有百度广告的游戏到App Store被拒，理由如下，麻烦告知解决办法，万分感谢！

### ISSUE THREAD

**Issue by shi8tou** [unity-plugins/BaiDu-Unity-Plugin#5]
2016年11月12日 上午2:19
发件人 Apple
		2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS
		3. 2.2 BUSINESS: OTHER BUSINESS MODEL ISSUES - UNACCEPTABLE
Performance - 2.5.2

During review, your app installed or launched executable code, which is not in compliance with the App Store Review Guidelines. Specifically, your app uses the itms-services URL scheme to install an application.

Next Steps

Please revise your app to remove this functionality.

Resources

Business - 3.2.2

The Baidu MobAd in your app displays or promotes third-party apps, which does not comply with the App Store Review Guidelines.

Next Steps

Please remove the Baidu MobAd feature from your app.

If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

**Comment by unity-plugins** [comment]
后面我测试下看看

**Comment by unity-plugins** [comment]
updated

**Comment by shi8tou** [comment]
非常感谢你的更新，但是这次xcode编译的过程中又报以下错误，麻烦帮忙看看。

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in BaiduMobAdSDK(BaiduMobAdActionComposer.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by unity-plugins** [comment]
加 SafariService.Framework

**Comment by shi8tou** [comment]
加了，没有报错了，编译通过，可是没有banner广告了，根本不展示广告了。麻烦帮忙再看看呢，多谢。
